export const TURMAS = [
  "1º ano - 929 - Automação",
  "1º ano - 930 - Des. de Sistema",
  "1º ano - 931 - Eletromecânica",
  "1º ano - 932 - IOT",
  "1º ano - 933 - Mecânica",
  "1º ano - 935 - Mecatrônica",
  "2º ano - 881 - Automação",
  "2º ano - 912 - Des. de Sistemas",
  "2º ano - 915 - Eletromecânica",
  "2º ano - 918 - IOT",
  "2º ano - 919 - Mecatrônica",
  "2º ano - 920 - Mecânica",
  "3º ano - 921 - Automação",
  "3º ano - 922 - Des. de Sistemas",
  "3º ano - 923 - Eletromecânica",
  "3º ano - 924 - IOT",
  "3º ano - 925 - Mecânica",
  "3º ano - 926 - Mecatrônica",
];

export const ALL_SUBJECTS = [
  { id: "matematica", name: "Matemática" },
  { id: "portugues", name: "Português" },
  { id: "historia", name: "História" },
  { id: "geografia", name: "Geografia" },
  { id: "ciencias", name: "Ciências" },
  { id: "fisica", name: "Física" },
  { id: "quimica", name: "Química" },
  { id: "biologia", name: "Biologia" },
  { id: "ingles", name: "Inglês" },
  { id: "logica", name: "Lógica" },
];

export const SAMPLE_QUESTIONS_BY_SUBJECT: Record<string, Array<{ q: string; options: string[]; correct: string }>> = {
  matematica: [
    { q: "Quanto é 15 × 8?", options: ["110", "120", "130", "140"], correct: "120" },
    { q: "Quanto é 144 ÷ 12?", options: ["10", "11", "12", "13"], correct: "12" },
    { q: "Quanto é 7² + 3²?", options: ["52", "58", "49", "40"], correct: "58" },
    { q: "Qual a raiz quadrada de 169?", options: ["11", "12", "13", "14"], correct: "13" },
    { q: "Quanto é 25% de 200?", options: ["25", "40", "50", "75"], correct: "50" },
  ],
  portugues: [
    { q: "Qual é o sujeito de 'O gato dormiu'?", options: ["gato", "dormiu", "O", "o gato"], correct: "o gato" },
    { q: "Qual palavra é um advérbio?", options: ["bonito", "rapidamente", "casa", "azul"], correct: "rapidamente" },
    { q: "'Ela chegou cedo.' O verbo é:", options: ["Ela", "chegou", "cedo", "Nenhum"], correct: "chegou" },
    { q: "Qual frase tem erro ortográfico?", options: ["Exceção", "Essessão", "Excesso", "Extensão"], correct: "Essessão" },
    { q: "Sinônimo de 'efêmero':", options: ["eterno", "passageiro", "forte", "lento"], correct: "passageiro" },
  ],
  historia: [
    { q: "Quem proclamou a Independência do Brasil?", options: ["D. Pedro I", "D. Pedro II", "Tiradentes", "Getúlio"], correct: "D. Pedro I" },
    { q: "Em que ano foi a Proclamação da República?", options: ["1822", "1889", "1891", "1930"], correct: "1889" },
    { q: "Qual civilização construiu as pirâmides de Gizé?", options: ["Romana", "Grega", "Egípcia", "Maia"], correct: "Egípcia" },
    { q: "A Revolução Francesa ocorreu em:", options: ["1776", "1789", "1815", "1848"], correct: "1789" },
    { q: "Quem foi o primeiro presidente do Brasil?", options: ["Getúlio Vargas", "Deodoro da Fonseca", "Prudente de Morais", "D. Pedro II"], correct: "Deodoro da Fonseca" },
  ],
  geografia: [
    { q: "Qual é o maior país do mundo em área?", options: ["China", "EUA", "Rússia", "Brasil"], correct: "Rússia" },
    { q: "Qual o rio mais longo do mundo?", options: ["Amazonas", "Nilo", "Yangtzé", "Mississippi"], correct: "Nilo" },
    { q: "Quantos continentes existem?", options: ["5", "6", "7", "8"], correct: "7" },
    { q: "Qual bioma ocupa maior área no Brasil?", options: ["Cerrado", "Amazônia", "Caatinga", "Mata Atlântica"], correct: "Amazônia" },
    { q: "Capital da Austrália:", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correct: "Canberra" },
  ],
  ciencias: [
    { q: "Qual gás as plantas absorvem na fotossíntese?", options: ["Oxigênio", "Nitrogênio", "CO₂", "Hidrogênio"], correct: "CO₂" },
    { q: "Quantos ossos tem o corpo humano adulto?", options: ["196", "206", "216", "256"], correct: "206" },
    { q: "Qual é a fórmula da água?", options: ["H₂O", "CO₂", "NaCl", "O₂"], correct: "H₂O" },
    { q: "Qual órgão bombeia sangue?", options: ["Pulmão", "Fígado", "Coração", "Rim"], correct: "Coração" },
    { q: "A célula é a unidade básica da:", options: ["matéria", "vida", "energia", "química"], correct: "vida" },
  ],
  fisica: [
    { q: "Qual a unidade de força no SI?", options: ["Joule", "Newton", "Watt", "Pascal"], correct: "Newton" },
    { q: "Velocidade = distância ÷ ___", options: ["massa", "tempo", "força", "aceleração"], correct: "tempo" },
    { q: "Qual a aceleração da gravidade (aprox.)?", options: ["8,9 m/s²", "9,8 m/s²", "10,8 m/s²", "7,8 m/s²"], correct: "9,8 m/s²" },
    { q: "A energia cinética depende de:", options: ["cor e forma", "massa e velocidade", "tempo e distância", "peso e altura"], correct: "massa e velocidade" },
    { q: "Qual tipo de energia um objeto em altura possui?", options: ["Cinética", "Térmica", "Potencial gravitacional", "Elétrica"], correct: "Potencial gravitacional" },
  ],
  quimica: [
    { q: "Qual elemento tem símbolo 'O'?", options: ["Ouro", "Ósmio", "Oxigênio", "Óganesson"], correct: "Oxigênio" },
    { q: "Quantos elementos tem a tabela periódica atual?", options: ["108", "112", "118", "120"], correct: "118" },
    { q: "pH 7 indica solução:", options: ["ácida", "básica", "neutra", "instável"], correct: "neutra" },
    { q: "NaCl é o nome químico de:", options: ["açúcar", "sal de cozinha", "vinagre", "álcool"], correct: "sal de cozinha" },
    { q: "Qual partícula tem carga negativa?", options: ["Próton", "Nêutron", "Elétron", "Fóton"], correct: "Elétron" },
  ],
  biologia: [
    { q: "DNA significa:", options: ["Ácido desoxirribonucleico", "Ácido dinitrogênico", "Átomo dinuclear", "Nenhuma"], correct: "Ácido desoxirribonucleico" },
    { q: "Mitocôndria é responsável por:", options: ["digestão", "respiração celular", "fotossíntese", "reprodução"], correct: "respiração celular" },
    { q: "Qual reino inclui os fungos?", options: ["Plantae", "Animalia", "Fungi", "Protista"], correct: "Fungi" },
    { q: "Quantos cromossomos tem o ser humano?", options: ["23", "44", "46", "48"], correct: "46" },
    { q: "Evolução foi proposta por:", options: ["Newton", "Einstein", "Darwin", "Mendel"], correct: "Darwin" },
  ],
  ingles: [
    { q: "Translate: 'Eu sou estudante'", options: ["I am student", "I am a student", "I is student", "Me am student"], correct: "I am a student" },
    { q: "Past tense of 'go':", options: ["goed", "went", "gone", "going"], correct: "went" },
    { q: "'She ___ a book.' (present)", options: ["read", "reads", "reading", "readed"], correct: "reads" },
    { q: "Opposite of 'hot':", options: ["warm", "cold", "cool", "ice"], correct: "cold" },
    { q: "'They ___ playing football.' (now)", options: ["is", "was", "are", "be"], correct: "are" },
  ],
  logica: [
    { q: "Se A=2 e B=3, quanto é A+B×2?", options: ["10", "8", "7", "12"], correct: "8" },
    { q: "Próximo: 2, 4, 8, 16, ...", options: ["20", "24", "32", "30"], correct: "32" },
    { q: "Se todo gato é animal, e Rex é gato, então:", options: ["Rex é planta", "Rex é animal", "Rex voa", "Nenhuma"], correct: "Rex é animal" },
    { q: "Quantos triângulos em um quadrado com diagonal?", options: ["1", "2", "3", "4"], correct: "2" },
    { q: "3! (fatorial) é igual a:", options: ["3", "6", "9", "12"], correct: "6" },
  ],
};
